

service: crowdingless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource:
        - "*"

environment:
  DYNAMODB_EMPLOYEE_TABLE: employeeTable

functions:
  create: 
    handler: employee.create
    events:
      - http:
          path: /v1/employee
          method: post
  list: 
    handler: employee.list
    events:
      - http:
          path: /v1/employee
          method: get
  get: 
    handler: employee.get
    events:
      - http:
          path: /v1/employee/{email}
          method: get
  update: 
    handler: employee.update
    events:
      - http:
          path: /v1/employee/{email}
          method: put
  delete: 
    handler: employee.delete
    events:
      - http:
          path: /v1/employee/{email}
          method: delete
  optimize:
    handler: optimize.handle
    environment: 
      bucket: bucketimagecrowdingless
    events:
      - s3:
          bucket: bucketimagecrowdingless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
      - s3:
          bucket: bucketimagecrowdingless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png
      - s3:
          bucket: bucketimagecrowdingless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpeg
