

service: crowdingless
# account serverless
# tenant: joaobispo2077 
# app: crowdingless-api 

frameworkVersion: '2'

plugins:
  # - serverless-s3-local
  # - serverless-dynamodb-local
  - serverless-step-functions
  # - serverless-offline

custom:
  EMPLOYEE_TABLE: crowdingless-employees-${opt:stage}

stepFunctions:
  validate: true
  stateMachines:
    sendEmail: 
      name: sendEmail
      events:
        - http:
              path: /v1/email/
              method: POST
              cors: true
      definition: ${file(./stepFunctions.yml)}


provider:
  apiGateway:
      binaryMediaTypes:
          - 'multipart/form-data'
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 512
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
        - s3:GetObject
        - s3:PutObject
        - dynamodb:PutItem
        - dynamodb:Scan*
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:s3:::*"
        - "arn:aws:dynamodb:sa-east-1:*:table/crowdingless-employees-${opt:stage}"
        - "arn:aws:ses:sa-east-1:*:identity/*"
        - "arn:aws:ses:sa-east-1:998571726230:identity/joaobispo2077@gmail.com"


  environment:
    DYNAMODB_EMPLOYEE_TABLE: ${self:custom.EMPLOYEE_TABLE}
    bucket: bucketimagecrowdingless

functions:
  crowdingless-api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
  create: 
    handler: employee.create
    events:
      - http:
          path: /v1/employee
          method: post
  list: 
    handler: employee.list
    events:
      - http:
          path: /v1/employee
          method: get
  get: 
    handler: employee.get
    events:
      - http:
          path: /v1/employee/{email}
          method: get
  update: 
    handler: employee.update
    events:
      - http:
          path: /v1/employee/{email}
          method: patch
  delete: 
    handler: employee.delete
    events:
      - http:
          path: /v1/employee/{email}
          method: delete
  optimize:
    handler: optimize.handle
    environment: 
      bucket: bucketimagecrowdingless
    events:
      - s3:
          bucket: bucketimagecrowdingless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
      - s3:
          bucket: bucketimagecrowdingless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png
      - s3:
          bucket: bucketimagecrowdingless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpeg
  addEmailToDB: 
    handler: src/lambdas/stepFunctionLambdas/addEmailToDB.handler
  readDynamo: 
    handler: src/lambdas/stepFunctionLambdas/readDynamo.handler
  sendEmail: 
    handler: src/lambdas/stepFunctionLambdas/sendEmail.handler

resources:
  Resources: 
    employeeTable: 
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.EMPLOYEE_TABLE}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

